name: release-please (package)

on:
  pull_request:
    types: [labeled]
    branches:
      - release-please--**


permissions:
  contents: write
  pull-requests: write

jobs:
  package:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'autorelease: pending'
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - run: npm run package

      - name: add commit
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add ./dist
          git commit --amend --no-edit
          git push origin HEAD
